module.exports = {
  purge: [
    "./src/components/dropdowns/aboutDropdown.js",
    "./src/components/dropdowns/programsDropdown.js",
    "./src/components/dropdowns/servicesDropdown.js",
    "./src/components/joinButtons/contract.js",
    "./src/components/joinButtons/contract24.js",
    "./src/components/joinButtons/noContract.js",
    "./src/components/joinButtons/noContract24.js",
    "./src/components/joinButtons/special.js",
    "./src/components/joinButtons/special24.js",
    "./src/components/aboutPMI.js",
    "./src/components/contactUs.js",
    "./src/components/explore2.js",
    "./src/components/footer.js",
    "./src/components/hero2.js",
    "./src/components/join.js",
    "./src/components/layout.js",
    "./src/components/logoCloud.js",
    "./src/components/m2mMembership.js",
    "./src/components/massage.js",
    "./src/components/membership2.js",
    "./src/components/membershipCard2.js",
    "./src/components/navLarge.js",
    "./src/components/navSmall.js",
    "./src/components/personal-training.js",
    "./src/components/pricingCard.js",
    "./src/components/programs.js",
    "./src/components/seo.js",
    "./src/components/successComponent.js",
    "./src/components/tanning.js",
    "./src/components/tetimonial.js",
    "./src/components/tetimonials.js",
    "./src/pages/404.js",
    "./src/pages/about.js",
    "./src/pages/classes.js",
    "./src/pages/contact.js",
    "./src/pages/hours.js",
    "./src/pages/index.js",
    "./src/pages/jobs.js",
    "./src/pages/membership.js",
    "./src/pages/privacy-policy.js",
    "./src/pages/programs.js",
    "./src/pages/services.js",
    "./src/pages/success.js",
  ],
  theme: {
    extend: {
      zIndex: {
        "-10": "-10",
      },
      colors: {
        "primary-dark": "#4d0187",
        primary: "#4d0187",
        "primary-light": "#927EBE",
        "secondary-light": "#50B8BB",
        secondary: "#1d8588",
        "secondary-dark": "#005255",
        background: "#ece9f0",
      },
      height: {
        "screen-50": "50vh",
        half: "50%",
      },
      fontSize: {
        huge: "3.5rem",
      },
      inset: {
        "-6": "-1.5rem",
      },
      maxWidth: {
        "50": "50%",
      },
    },
  },
  variants: {},
  plugins: [],
}
